apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZV3hsZUhKMVpXczZaMmh3WDI1eU5HNHdkMjl5UVdvMmRFcEZWSGQzVmpZNWVYUm5jMUo2UkZwUk5qRnFNRGcwVFE9PSJ9fX0K
type: kubernetes.io/dockerconfigjson